spring:
  application:
    name: club-service

#  flyway:
#    url: ${FLYWAY_URL}
#    baseline-on-migrate: true
#    enabled: true
#    user: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
    # ddl-auto: validate
        ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        show_sql: true
        format_sql: true

app:
  gateway:
    endpoint: https://gateway.gachdong.club

logging:
  level:
    org.hibernate.SQL: DEBUG

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,metrics,prometheus
#  tracing:
#    sampling:
#      probability: 1.0
#    enabled: false

