spring:
  datasource:
    url: jdbc:h2:mem:testdb  # 임시 데이터베이스로 H2 사용
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # 테스트 실행 시 스키마 생성 및 삭제
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace