spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://gach-dong-dev.club"
              - "https://gateway.gach-dong.club"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
      routes:
        - id: club-service
          uri: http://club-service:8080
          predicates:
            - Path=/gachdong/club/**
          filters:
            - RewritePath=/gachdong/club/(?<segment>.*), /club/${segment}

        - id: club-service-swagger
          uri: http://club-service:8080
          predicates:
            - Path=/gachdong/club/v3/api-docs/**
          filters:
            - RewritePath=/gachdong/club/v3/api-docs/(?<segment>.*), /club/v3/api-docs/${segment}

        - id: club-service-swagger-ui
          uri: http://club-service:8080
          predicates:
            - Path=/gachdong/club/swagger-ui/**
          filters:
            - RewritePath=/gachdong/club/swagger-ui/(?<segment>.*), /club/swagger-ui/${segment}

springdoc:
  swagger-ui:
    enabled: true
    urls[0]:
      name: "동아리 서비스"
      url: https://gateway.gachdong.club/club/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: trace
    reactor.netty: trace

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,metrics,prometheus
#  tracing:
#    sampling:
#      probability: 1.0
#    enabled: false

#app:
#  jwt:
#    verify-key: ${JWT_VERIFY_KEY}